// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kolos2pod2.Models;

namespace kolos2pod2.Migrations
{
    [DbContext(typeof(MainDbContext))]
    partial class MainDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("kolos2pod2.Models.File", b =>
                {
                    b.Property<int>("FileID")
                        .HasColumnType("int");

                    b.Property<int>("TeamID")
                        .HasColumnType("int");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FileSize")
                        .HasColumnType("int");

                    b.HasKey("FileID", "TeamID");

                    b.HasIndex("TeamID");

                    b.ToTable("File");

                    b.HasData(
                        new
                        {
                            FileID = 1,
                            TeamID = 2,
                            FileExtension = "abcd",
                            FileName = "Jan",
                            FileSize = 4
                        },
                        new
                        {
                            FileID = 2,
                            TeamID = 1,
                            FileExtension = "dbcd",
                            FileName = "Adam",
                            FileSize = 4
                        });
                });

            modelBuilder.Entity("kolos2pod2.Models.Member", b =>
                {
                    b.Property<int>("MemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MemberName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MemberNickName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MemberSurname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OrganizationID")
                        .HasColumnType("int");

                    b.HasKey("MemberID");

                    b.HasIndex("OrganizationID");

                    b.ToTable("Member");

                    b.HasData(
                        new
                        {
                            MemberID = 1,
                            MemberName = "cos1 ",
                            MemberNickName = "Kos",
                            MemberSurname = "ON",
                            OrganizationID = 2
                        },
                        new
                        {
                            MemberID = 2,
                            MemberName = "cos2",
                            MemberNickName = "Trzos",
                            MemberSurname = "DP",
                            OrganizationID = 1
                        });
                });

            modelBuilder.Entity("kolos2pod2.Models.Membership", b =>
                {
                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<int>("TeamID")
                        .HasColumnType("int");

                    b.Property<DateTime>("MembershipDate")
                        .HasColumnType("datetime2");

                    b.HasKey("MemberID", "TeamID");

                    b.HasIndex("TeamID");

                    b.ToTable("Membership");

                    b.HasData(
                        new
                        {
                            MemberID = 1,
                            TeamID = 2,
                            MembershipDate = new DateTime(2022, 6, 23, 11, 26, 23, 145, DateTimeKind.Local).AddTicks(8191)
                        },
                        new
                        {
                            MemberID = 2,
                            TeamID = 1,
                            MembershipDate = new DateTime(2022, 6, 23, 11, 26, 23, 147, DateTimeKind.Local).AddTicks(6591)
                        });
                });

            modelBuilder.Entity("kolos2pod2.Models.Organization", b =>
                {
                    b.Property<int>("OrganizationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OrganizationDomain")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("OrganizationID");

                    b.ToTable("Organization");

                    b.HasData(
                        new
                        {
                            OrganizationID = 1,
                            OrganizationDomain = "nwm",
                            OrganizationName = "123"
                        },
                        new
                        {
                            OrganizationID = 2,
                            OrganizationDomain = "pomocy",
                            OrganizationName = "321"
                        });
                });

            modelBuilder.Entity("kolos2pod2.Models.Team", b =>
                {
                    b.Property<int>("TeamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OrganizationID")
                        .HasColumnType("int");

                    b.Property<string>("TeamDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("TeamID");

                    b.HasIndex("OrganizationID");

                    b.ToTable("Team");

                    b.HasData(
                        new
                        {
                            TeamID = 1,
                            OrganizationID = 0,
                            TeamDescription = "cos se tam robia",
                            TeamName = "KOWALELOSU"
                        },
                        new
                        {
                            TeamID = 2,
                            OrganizationID = 0,
                            TeamDescription = "praca praca praca",
                            TeamName = "MAESTRO"
                        });
                });

            modelBuilder.Entity("kolos2pod2.Models.File", b =>
                {
                    b.HasOne("kolos2pod2.Models.Team", "Team")
                        .WithMany("File")
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("kolos2pod2.Models.Member", b =>
                {
                    b.HasOne("kolos2pod2.Models.Organization", "Organization")
                        .WithMany("Member")
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("kolos2pod2.Models.Membership", b =>
                {
                    b.HasOne("kolos2pod2.Models.Member", "Member")
                        .WithMany("Membership")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kolos2pod2.Models.Team", "Team")
                        .WithMany("Membership")
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("kolos2pod2.Models.Team", b =>
                {
                    b.HasOne("kolos2pod2.Models.Organization", "Organization")
                        .WithMany("Team")
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("kolos2pod2.Models.Member", b =>
                {
                    b.Navigation("Membership");
                });

            modelBuilder.Entity("kolos2pod2.Models.Organization", b =>
                {
                    b.Navigation("Member");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("kolos2pod2.Models.Team", b =>
                {
                    b.Navigation("File");

                    b.Navigation("Membership");
                });
#pragma warning restore 612, 618
        }
    }
}
